In [2]:
import numpy as np

arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr + 5 
arr -2 
#take every element and add 5 in each element

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr/arr

C:\Users\sapana subedi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
#normally what happens is if i divide 1 by 0, in normal python you will get an error but when it comes to numpy array, it just shows warning and show a placeholder of infinity. replace with nan or infinity
#1/0

#1/arr

In [8]:
1/arr

C:\Users\sapana subedi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [12]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [14]:
np.log(arr)

C:\Users\sapana subedi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr.mean()


4.5

In [17]:
arr.max()

9

In [18]:
arr.sum()

45

In [19]:
arr.std()

2.8722813232690143

In [20]:
arr.var()

8.25

In [26]:
#2-D array

arr2d = np.arange(0,20).reshape(5,4)

arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [32]:
arr2d.shape #row then col

(5, 4)

In [33]:
arr2d.sum()

190

In [34]:
arr2d.sum(axis = 0) #the element at index 0 is row, perform operation across rows

array([40, 45, 50, 55])

In [35]:
arr2d.sum(axis = 1) #perform operation across columns

array([ 6, 22, 38, 54, 70])

In [39]:
import numpy as np
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])


account_total =  account_transactions.sum()
account_total

2720