In [ ]:
## What Numpy is?
py libraries for creating n dimentional arrays
quickly broadcast functions
looks similial to python lists


In [ ]:
#Numpy arrays



In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

type(mylist)

list

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
myarr = np.array(mylist)

In [5]:
type(myarr)

numpy.ndarray

In [11]:
my_matrix =[[1,2,3], [4,5,6], [8,9,0]]

In [9]:
type(my_matrix)
my_matrix

[[1, 2, 3], [4, 5, 6, 7], [8, 9, 0]]

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 0]])

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
#floating point number--1D
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
#2 rows, 5 column
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
#evenly spaced: len()

np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.random.rand(2,4)

array([[0.90553743, 0.11912465, 0.88980476, 0.60835728],
       [0.99820206, 0.55534232, 0.29112566, 0.35401086]])

In [32]:
np.random.randn(10)

array([-0.92626944, -0.14439095,  0.53849137, -0.87751781, -1.1505814 ,
        0.60338163, -1.08472539, -0.21693186, -0.02661602,  0.2862073 ])

In [35]:
np.random.randint(0,200, 9)
#shape (4 by 5)
np.random.randint(0,200, (4,5))


array([[161,  79, 156, 121, 108],
       [ 55, 124, 120,  33,  81],
       [ 61, 129, 145,  71, 130],
       [193,   1, 184,  85,  29]])

In [37]:
np.random.seed(42) #seed value #arbitary number
np.random.rand(4) #4 number betn 0 & 1

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [38]:
np.random.rand(4) #4 number betn 0 & 1

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [40]:
arr = np.arange(0,25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
ranarr = np.random.randint(0,101,10)
ranarr

array([58, 41, 91, 59, 79, 14, 61, 61, 46, 61])

In [44]:
ranarr.max()

91

In [45]:
ranarr.min()

14

In [46]:
#argmin, argmax, dtype

In [47]:
arr.shape


(25,)

In [50]:
reshape =arr.reshape(5,5)
reshape


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])