In [1]:
import numpy as np

In [3]:
#### Create an array of 10 zeros

arr10Zeros = np.zeros(10)
arr10Zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
#### Create an array of 10 ones

arr10Ones = np.ones(10)
arr10Ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
#### Create an array of 10 fives

arr10Fives = arr10Zeros+5
arr10Fives



array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [9]:
#### Create an array of the integers from 10 to 50

arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [33]:
#### Create an array of all the even integers from 10 to 50

arrEven = np.arange(10,51,2)
arrEven




array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [25]:
#### Create a 3x3 matrix with values ranging from 0 to 8

arrMatrix = np.arange(0,9).reshape(3,3)
arrMatrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
#### Create a 3x3 identity matrix

arrMatrixIdentity = np.eye(3,3)
arrMatrixIdentity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
#### Use NumPy to generate a random number between 0 and 1

arrRandom = np.random.rand(1)
arrRandom

array([0.32555083])

In [42]:
#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

arrStandardNormalDistribution = np.random.randn(25)
arrStandardNormalDistribution

array([ 1.91992916,  0.53200266,  0.0081838 , -0.07955638, -0.6658603 ,
       -1.43021337,  1.63417998,  1.06269539, -0.72134747, -1.43091418,
       -1.49713611, -0.15574599, -0.27895099, -0.06051791, -0.5718884 ,
       -0.0980062 ,  0.44669324,  0.50796842, -0.53183853,  1.20343268,
        1.33504197, -1.04226951, -2.51319887,  0.6897442 , -0.19387153])

In [48]:
#### Create an array of 20 linearly spaced points between 0 and 1:

arrLinearlySpaced = np.arange(1, 101)/100
arrLinearlySpaced.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [52]:
#### Create an array of 20 linearly spaced points between 0 and 1:

# arrLinearlySpaced = np.arange(1,2)
# arrLinearlySpaced.reshape(5,4)

arrLinearlySpaced = np.linspace(0,1,20)

arrLinearlySpaced



array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [16]:
## Numpy Indexing and Selection

In [54]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [55]:
mat[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [56]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [57]:
mat[3,4]

20

In [58]:
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [59]:
mat[4,:] # this simply means row 4 all the columns

array([21, 22, 23, 24, 25])

In [60]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [61]:
mat[3:5, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [62]:
### Numpy Operations

###Get the sum of all the values in mat
mat.sum()

325

In [63]:
##Get the standard deviation of the values in mat

mat.std()

7.211102550927978

In [64]:
##Get the sum of all the column in mat

mat.sum(axis = 0)

array([55, 60, 65, 70, 75])

In [65]:
np.random.seed(101)
np.random.rand(1)

array([0.51639863])